version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t downpage .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" != "release" ]; then
              if [ "${CIRCLE_PROJECT_USERNAME}" == "akkeris" ]; then 
                docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
                docker tag downpage "docker.io/akkeris/downpage:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                docker push "docker.io/akkeris/downpage:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}"
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  docker tag downpage "docker.io/akkeris/downpage:release-${CIRCLE_BUILD_NUM}"
                  docker tag downpage "docker.io/akkeris/downpage:latest"
                  docker push "docker.io/akkeris/downpage:latest"
                  docker push "docker.io/akkeris/downpage:release-${CIRCLE_BUILD_NUM}"
                fi
              fi
            fi
